#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

"$ROOT/tools/discover-purebasic.sh"
"$ROOT/tools/test.sh"
"$ROOT/tools/build.sh"
"$ROOT/.build/examples/000-project-foundation/console_probe"
"$ROOT/.build/examples/001-framing/framing_probe"
"$ROOT/.build/examples/002-transport-codecs/stdio_codec_probe"
"$ROOT/.build/examples/003-connection-lifecycle/connection_probe"
"$ROOT/.build/examples/004-protocol-errors/spec_examples_probe"
"$ROOT/.build/examples/005-dispatch/dispatch_probe"
"$ROOT/.build/examples/006-outbound-requests/outbound_probe"
"$ROOT/.build/examples/007-timeout-housekeeping/timeout_probe"
"$ROOT/.build/examples/008-batch-handling/batch_probe"
"$ROOT/.build/examples/009-cancellation/cancel_probe"
"$ROOT/.build/examples/010-diagnostics/diagnostics_probe"
"$ROOT/.build/examples/011-stress-memory/stress_probe"
"$ROOT/.build/examples/012-stdio-runtime-pump/stdio_runtime_probe"
"$ROOT/.build/examples/013-mcp-lifecycle/mcp_lifecycle_probe"
"$ROOT/.build/examples/014-mcp-tools-registry/mcp_tools_list_probe"
"$ROOT/.build/examples/015-mcp-tools-call/mcp_tools_call_probe"
"$ROOT/.build/examples/016-packaging-docs/package_probe"
"$ROOT/.build/examples/017-reader-writer-interfaces/io_probe"
"$ROOT/.build/examples/018-byte-buffer-framing/byte_buffer_probe"
"$ROOT/.build/examples/019-connection-events/events_probe"
"$ROOT/.build/examples/020-handler-registration-lifecycle/handler_lifecycle_probe"
"$ROOT/.build/examples/021-handler-cancellation-tokens/cancellation_token_probe"
