#!/usr/bin/env sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
. "$ROOT/tools/pb-env.sh"

pb_prepare_dirs
pb_create_local_homes
pb_require_tools

compiler_version="$(pb_compiler_version | sed -n '1p')"
pureunit_version="$(pb_pureunit_version | sed -n '1p')"

cat > "$ROOT/.local/purebasic-home/env.sh" <<EOF_ENV
# Generated by tools/discover-purebasic.sh
export PB_PROJECT_ROOT='$ROOT'
export PB_INSTALL_HOME='$PB_INSTALL_HOME'
export PB_HOME='$PB_HOME'
export PUREBASIC_HOME='$PUREBASIC_HOME'
export PB_COMPILER='$PB_COMPILER'
EOF_ENV

cat > "$ROOT/.local/pureunit-home/env.sh" <<EOF_ENV
# Generated by tools/discover-purebasic.sh
export PUREUNIT_HOME='$PUREUNIT_HOME'
export PUREUNIT='$PUREUNIT'
EOF_ENV

cat > "$ROOT/.local/toolchain-summary.txt" <<EOF_SUMMARY
PureBasic JSON-RPC local toolchain

Project root: $ROOT
PureBasic install home: $PB_INSTALL_HOME
PureBasic home: $PB_HOME
PureBasic compiler: $PB_COMPILER
Compiler version: $compiler_version
PureUnit home: $PUREUNIT_HOME
PureUnit runner: $PUREUNIT
PureUnit version: $pureunit_version
EOF_SUMMARY

pb_print_summary
printf 'Generated local homes under .local/.\n'
