#!/usr/bin/env sh

pbp_each_project_target() {
  callback="$1"

  "$callback" "PureBasic-JSON-RPC.pbp" "jsonrpc alpha verification" "console" ".build/PureBasic-JSON-RPC/jsonrpc_alpha_verification" "root JSON-RPC project"
  "$callback" "examples/000-project-foundation/project_foundation.pbp" "console_probe" "console" ".build/examples/000-project-foundation/console_probe" "console scenario"
  "$callback" "examples/001-framing/framing.pbp" "framing_probe" "console" ".build/examples/001-framing/framing_probe" "framing scenario"
  "$callback" "examples/002-transport-codecs/transport_codecs.pbp" "stdio_codec_probe" "console" ".build/examples/002-transport-codecs/stdio_codec_probe" "stdio codec scenario"
  "$callback" "examples/003-connection-lifecycle/connection_lifecycle.pbp" "connection_probe" "console" ".build/examples/003-connection-lifecycle/connection_probe" "connection scenario"
  "$callback" "examples/004-protocol-errors/protocol_errors.pbp" "spec_examples_probe" "console" ".build/examples/004-protocol-errors/spec_examples_probe" "protocol errors scenario"
  "$callback" "examples/005-dispatch/dispatch.pbp" "dispatch_probe" "console" ".build/examples/005-dispatch/dispatch_probe" "dispatch scenario"
  "$callback" "examples/006-outbound-requests/outbound_requests.pbp" "outbound_probe" "console" ".build/examples/006-outbound-requests/outbound_probe" "outbound requests scenario"
  "$callback" "examples/007-timeout-housekeeping/timeout_housekeeping.pbp" "timeout_probe" "console" ".build/examples/007-timeout-housekeeping/timeout_probe" "timeout housekeeping scenario"
  "$callback" "examples/008-batch-handling/batch_handling.pbp" "batch_probe" "console" ".build/examples/008-batch-handling/batch_probe" "batch handling scenario"
  "$callback" "examples/009-cancellation/cancellation.pbp" "cancel_probe" "console" ".build/examples/009-cancellation/cancel_probe" "cancellation scenario"
  "$callback" "examples/010-diagnostics/diagnostics.pbp" "diagnostics_probe" "console" ".build/examples/010-diagnostics/diagnostics_probe" "diagnostics scenario"
  "$callback" "examples/011-stress-memory/stress_memory.pbp" "stress_probe" "console" ".build/examples/011-stress-memory/stress_probe" "stress memory scenario"
  "$callback" "examples/012-stdio-runtime-pump/stdio_runtime_pump.pbp" "stdio_runtime_probe" "console" ".build/examples/012-stdio-runtime-pump/stdio_runtime_probe" "stdio runtime scenario"
  "$callback" "examples/013-mcp-lifecycle/mcp_lifecycle.pbp" "mcp_lifecycle_probe" "console" ".build/examples/013-mcp-lifecycle/mcp_lifecycle_probe" "MCP lifecycle scenario"
  "$callback" "examples/014-mcp-tools-registry/mcp_tools_registry.pbp" "mcp_tools_list_probe" "console" ".build/examples/014-mcp-tools-registry/mcp_tools_list_probe" "MCP tools list scenario"
  "$callback" "examples/015-mcp-tools-call/mcp_tools_call.pbp" "mcp_tools_call_probe" "console" ".build/examples/015-mcp-tools-call/mcp_tools_call_probe" "MCP tools call scenario"
  "$callback" "examples/016-packaging-docs/packaging_docs.pbp" "package_probe" "console" ".build/examples/016-packaging-docs/package_probe" "packaging docs scenario"
  "$callback" "examples/016-packaging-docs/packaging_docs.pbp" "console_template" "console" ".build/examples/016-packaging-docs/console_template" "console template"
  "$callback" "examples/016-packaging-docs/packaging_docs.pbp" "shared_library_template" "shared" ".build/examples/016-packaging-docs/shared_library_template.dylib" "shared library template"
  "$callback" "examples/016-packaging-docs/packaging_docs.pbp" "app_template" "executable" ".build/examples/016-packaging-docs/app_template" "app template"
  "$callback" "examples/017-reader-writer-interfaces/reader_writer_interfaces.pbp" "io_probe" "console" ".build/examples/017-reader-writer-interfaces/io_probe" "reader writer interfaces scenario"
  "$callback" "examples/018-byte-buffer-framing/byte_buffer_framing.pbp" "byte_buffer_probe" "console" ".build/examples/018-byte-buffer-framing/byte_buffer_probe" "byte buffer framing scenario"
  "$callback" "examples/019-connection-events/connection_events.pbp" "events_probe" "console" ".build/examples/019-connection-events/events_probe" "connection events scenario"
  "$callback" "examples/020-handler-registration-lifecycle/handler_registration_lifecycle.pbp" "handler_lifecycle_probe" "console" ".build/examples/020-handler-registration-lifecycle/handler_lifecycle_probe" "handler registration lifecycle scenario"
  "$callback" "examples/021-handler-cancellation-tokens/handler_cancellation_tokens.pbp" "cancellation_token_probe" "console" ".build/examples/021-handler-cancellation-tokens/cancellation_token_probe" "handler cancellation tokens scenario"
  "$callback" "examples/022-write-queue-close-semantics/write_queue_close_semantics.pbp" "write_queue_probe" "console" ".build/examples/022-write-queue-close-semantics/write_queue_probe" "write queue close semantics scenario"
  "$callback" "examples/023-trace-logger-hooks/trace_logger_hooks.pbp" "trace_probe" "console" ".build/examples/023-trace-logger-hooks/trace_probe" "trace logger hooks scenario"
  "$callback" "examples/024-compliance-suite/compliance_suite.pbp" "compliance_probe" "console" ".build/examples/024-compliance-suite/compliance_probe" "compliance suite scenario"
  "$callback" "examples/025-public-api-review/public_api_review.pbp" "api_review_probe" "console" ".build/examples/025-public-api-review/api_review_probe" "public API review scenario"
  "$callback" "examples/026-alpha-release-package/alpha_release_package.pbp" "alpha_package_probe" "console" ".build/examples/026-alpha-release-package/alpha_package_probe" "alpha release package scenario"
  "$callback" "examples/027-release-quality-gates/release_quality_gates.pbp" "release_quality_probe" "console" ".build/examples/027-release-quality-gates/release_quality_probe" "release quality gates scenario"
  "$callback" "MCP/examples/purebasic-check/purebasic_check.pbp" "purebasic/check stdio server" "console" ".build/MCP/examples/purebasic-check/purebasic_check_server" "MCP purebasic/check server"
  "$callback" "MCP/examples/sqlite-admin/sqlite_admin.pbp" "sqlite-admin stdio server" "console" ".build/MCP/examples/sqlite-admin/sqlite_admin_server" "MCP sqlite admin server"
  "$callback" "MCP/examples/sqlite-admin/sqlite_admin.pbp" "sqlite-admin bootstrap" "console" ".build/MCP/examples/sqlite-admin/sqlite_admin_bootstrap" "MCP sqlite admin bootstrap"
  "$callback" "MCP/examples/sqlite-admin/sqlite_admin.pbp" "sqlite-admin probe" "console" ".build/MCP/examples/sqlite-admin/sqlite_admin_probe" "MCP sqlite admin probe"
}
